GET http://localhost:8080/groups/add?groupName=IKBO-20-21.

###

GET http://localhost:8080/groups

###

GET http://localhost:8080/students/add?firstName=Alena&lastName=Yakovleva&groupId=1

###

GET http://localhost:8080/students

###


